### ISSUE TITLE
Add reference doc for CodeSandbox, including screenshots

### ISSUE THREAD

**Issue by amcgee** [dhis2/academy-web-app-dev-2020#4]

**Comment by Mohammer5** [comment]
Do you want screenshots of the code sandbox itself in the README's as well? My plan was to keep the readme as clean as possible so it works for both local development as well as code sandbox development, but instead show the code sandbox in the slides.

So basically with this in mind: slides = for the webinar, readme = more general learning material

**Comment by amcgee** [comment]
It doesn’t make much difference to me, so long as the screenshots (slides linked from the readme or images embedded in the readme) are accessible as référence material.

This issue is for adding a session specifically for instructions and tips about using code sandbox, not necessarily adding screenshots to the other sections.

I think we should probably require code sandbox for live workshop participants, so they can submit codesandbox links when done with their exercises.

**Comment by amcgee** [comment]
Closed in #6 🎉
